<hr style="border:5px solid #108999"> </hr>

# Python Variables and Types of Data <hr style="border:4.5px solid #108999"> </hr>

## Variables

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

Create a variable with name "x" and a value of 10. Execute.

In [1]:
x = 10

Tell the computer to show you the value of that variable.

In [2]:
x

10

Can you think of a second way to obtain the same result? 

In [3]:
print (x)

10


On the same line, create four new variables: a,b,c, and d, that are equal to 10, 20, 30, and 40, respectively.

In [4]:
a,b,c,d = (10,20,30,40)

Alternatively:

In [5]:
a,b,c,d = 10,20,30,40

Tell the computer to show you the value corresponding to the variable "b".

In [6]:
b

20

Alternatively:

In [7]:
print (b)

20


Do the same for "d".

In [8]:
d

40

Or:

In [9]:
print (d)

40


## Numbers and Boolean Values

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

Create a variable equal to "True".

In [1]:
a = True

Check its type.

In [2]:
type(a)

bool

Create a variable equal to 99.

In [3]:
b = 99

Check its type.

In [4]:
type(b)

int

Check the type of the value 0.99. 

In [5]:
type(0.99)

float

Turn 99 into a *float*.

In [6]:
float(b)

99.0

Turn 0.99 into an integer. What value did you get?

In [7]:
int(0.99)

0

## Strings

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

Assign the value of 100 to the variable "m".

In [1]:
m = 100

With the help of the variable "m", write one line of code where the output after executuion would be *100 days*.

*Hint:* *You could provide four answers to this question!*

In [2]:
print (str(m), 'days')

100 days


or:

In [3]:
print (str(m), "days")

100 days


or:

In [4]:
print (str(m) + ' days')

100 days


or:

In [5]:
print (str(m) + " days")

100 days


Produce an output equal to *It's cool, isn't it?*

In [6]:
print ('It\'s cool, isn\'t it?')

It's cool, isn't it?


or:

In [7]:
print ("It's cool, isn't it?")

It's cool, isn't it?


or:

In [8]:
print ("It\'s cool, isn\'t it?")

It's cool, isn't it?


Fix the string below.

In [9]:
'Don't be shy

SyntaxError: invalid syntax (<ipython-input-9-dff2d36701a4>, line 1)

In [10]:
"Don't be shy"

"Don't be shy"

Produce an output equal to *Click "OK"*.

In [11]:
print ('Click "OK"')

Click "OK"


Include a plus sign in your line of code to produce *'Big Houses'*.

In [12]:
'Big ' + 'Houses'

'Big Houses'

In [13]:
'Big' + ' Houses'

'Big Houses'

Include a trailing comma in your line of code to produce *Big Houses*.

In [14]:
print ('Big', 'Houses')

Big Houses


<hr style="border:5px solid #108999"> </hr>

# Basic Python Syntax <hr style="border:4.5px solid #108999"> </hr>

## Arithmetic operators

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

Combine 15 and 23.

In [1]:
15 + 23

38

Subtract 50 from 26.

In [2]:
26 - 50

-24

Divide 20 by 4.

In [3]:
20 / 4

5.0

Divide 22 by 4.

In [4]:
22 / 4

5.5

Obtain the remainder of the division of 22 by 4.

In [5]:
22 % 4

2

Divide the float 22 by 4.

In [6]:
float(22) / 4

5.5

or:

In [7]:
22.0 / 4

5.5

Multiply 6 by 8.

In [8]:
6 * 8

48

Raise 15 to the power of 2.

In [9]:
15 ** 2

225

## The double-equality sign

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

Demonstrate that 100 is not equal to 98.

In [1]:
100 == 98

False

## Reassign Values

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

Assign the value of 14 to a variable p.

In [1]:
p = 14

Calculate p + 10.

In [2]:
p + 10

24

Now, assign 30 to the variable p.

In [3]:
p = 30

Calculate p + 10.

In [4]:
p + 10

40

Observe how the value of p is always the last one you have assigned.

## Line Continuation

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

Add a backslash in the code below, so it is a one-line code. Observe the change in the result.

In [1]:
15 + 31
- 26

-26

In [2]:
15 + 31 \
- 26

20

## Indexing

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

Extract the letter 'B' from "Bingo!".

In [1]:
'Bingo!'[0]

'B'

In [2]:
"Bingo!"[0]

'B'

Extract the letter "u" from "Constitution".

In [3]:
"Constitution"[7]

'u'

In [4]:
'Constitution' [7]

'u'

## Structure Your Code with Indentation

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

Use indentation properly to print the result of the function with an argument of 3.

In [1]:
def ten(x):
    x = 10
    return x
    print (ten(3))

Solution:

In [2]:
def ten(x):
    x = 10
    return x
    
print (ten(3))

10


<hr style="border:5px solid #108999"> </hr>

# Operators <hr style="border:4.5px solid #108999"> </hr>

## Comparison Operators

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

Verify that 25 is smaller than 30. 

In [1]:
25 < 30

True

Verify that 5 multiplied by 3 is less than or equal to 5 to the power of 3. 

In [2]:
5 * 3 <= 5 ** 3

True

Verify that 100 is equal to 10 square.

In [3]:
100 == 10 ** 2

True

Verify that 53 is not equal to 46.

In [4]:
53 != 46

True

## Logical and Identity Operators

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

Check whether the following code is True or False.

False or not True and not False 

In [1]:
False or not True and not False 

False

True and not False and True or not False

In [2]:
True and not False and True or not False

True

True or False and False

In [3]:
True or False and False

True

False and True or False

In [4]:
False and True or False

False

Using an identity operator, verify that 10 is not the same as 12.

In [5]:
10 is not 12

True

Using an identity operator, verify that 50 is the same as 50.

In [6]:
50 is 50

True

<hr style="border:5px solid #108999"> </hr>

# Conditional Statements <hr style="border:4.5px solid #108999"> </hr>

## Introduction to the IF statement

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

Create a two-line code that prints "The condition has been satisfied" if 5 is greater than 2.

In [1]:
if 5 > 2:
    print ("The condition has been satisfied")

The condition has been satisfied


Assign 10 to the variable x and 25 to the variable y. In the same cell, create 2 conditional statements. Let the first one print "Both conditions are correct" if x is greater then 3 and y is greater than 13. Let the second one print "At least one of the conditions is false" if x is less than or equal to 3 or y is less than or equal to 13. 
Change the values assigned to x and y and re-run the cell to verify your code still works.

In [1]:
x = 10
y = 25

if x > 3 and y > 13:
    print ('Both conditions are correct')
if x <= 3 or y <= 13:
    print ('At least one of the conditions is false')

Both conditions are correct


## Add an ELSE Statement

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

Let x represent the number of orders received during a certain day. 
Assign 102 to x. Create a program that prints "A busy day" if x is greater than 100, and "A calm day" otherwise. Change x to 97 to verify your code works properly.

In [1]:
x = 102

if x > 100:
    print ("A busy day")
else:
    print ("A calm day")

A busy day


## Else if, for Brief - ELIF

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

Assign 200 to x.
Create the following piece of code:
If x > 200, print out "Big"; 
If x > 100 and x <= 200, print out "Average"; 
and If x <= 100, print out "Small".
Use the If, Elif, and Else keywords in your code.

Change the initial value of x to see how your output will vary.

In [1]:
x = 200

if x > 200: 
    print ("Big")
elif x > 100 and x <= 200:
    print ("Average")
else:
    print ("Small")    

Average


Keep the first two conditions of the previous code. Add a new ELIF statement, so that, eventually, the program prints "Small" if x >= 0 and x <= 100, and "Negative" if x < 0. 
Let x carry the value of 50 and then of -50 to check if your code is correct.

In [2]:
x = 200

if x > 200: 
    print ("Big")
elif x > 100 and x <= 200:
    print ("Average")
elif x >= 0 and x <= 100:
    print ("Small")  
else:
    print ("Negative")

Average


<hr style="border:5px solid #108999"> </hr>

# Functions <hr style="border:4.5px solid #108999"> </hr>

## Creating a Function with a Parameter

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

Define a function that returns a value equal to its argument multiplied by 2.

In [1]:
def multiplication_by_2(x):
    return x * 2

Define a funciton that returns a float value equal to its argument divided by 2.

In [2]:
def division_by_2(x):
    return float(x) / 2

or:

In [3]:
def divisin_by_2(x):
    return x / 2.0

# This is new to you - yes, the divisor could be set to be a float, and that would make your output a floating point, too!

## Another Way to Define a Function

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

Define a function that states the value of the argument accompanied by the phrase "Raised to the power of 2:" and returns a value equal to its argument raised to the power of 2. This time, use a new variable, called "result", in the body of the Function. 
Call the function with some argument to verify it works properly.

*Hint: Your knowledge about stating multiple elements on a line can be of great help in solving this exercise!*

In [1]:
def exponentiation_exp_2(x):
    result = x ** 2
    print (x, "Raised to the power of 2:")
    return result

In [2]:
exponentiation_exp_2(5)

5 Raised to the power of 2:


25

## Using a Function in Another Function

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

Define a function that adds 5 to the parameter. Then, define another function that will multiply the newly obtained number by 3.
Verify your code was correct by calling the second function with an argument of 5. 
Was your output equal to 30?

In [1]:
def plus_five(x):
    return x + 5

def m_by_3(x):
    return plus_five(x) * 3

In [2]:
m_by_3(5)

30

## Combining Conditional Statements and Functions

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

Define a function, called **compare_the_two()**, with two arguments. If the first one is greater than the second one, let it print "Greater". If the second one is greater, it should print "Less". Let it print "Equal" if the two values are the same number.

In [1]:
def compare_the_two(x,y):
    if x > y:
        print ("Greater")
    elif x < y:
        print ("Less")
    else:
        print ("Equal")

In [2]:
compare_the_two(10,10)

Equal


## Notable Built-In Functions in Python

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

Obtain the maximum number among the values 25, 65, 890, and 15.

In [1]:
max(25, 65, 890, 15)

890

Obtain the minimum number among the values 25, 65, 890, and 15.

In [2]:
min(25, 65, 890, 15)

15

Find the absolute value of -100

In [3]:
abs(-100)

100

Round the value of 55.5. Did you obtain 56.0?

In [4]:
round(55.5)

56

Round 35.56789 to the third digit.

In [5]:
round(35.56789, 3)

35.568

Find the sum of all elements in the provided list, called "Numbers".

In [6]:
Numbers = [1, 5, 64, 24.5]

In [7]:
sum(Numbers)

94.5

Use a built-in function to raise 10 to the power of 3.

In [8]:
pow(10, 3)

1000

How many characters are there in the word "Elephant"?

In [9]:
len("Elephant")

8

Create a function, called "distance_from_zero", that returns the absolute value of a provided single argument and prints a statement "Not Possible" if the argument provided is not a number.
Call the funtion with the values of -10 and "cat" to verify it works correctly.

In [10]:
def distance_from_zero(x):
    if type(x) == int or type(x) == float:
        return abs(x)
    else:
        print ("Not possible")

In [11]:
distance_from_zero(-10)

10

In [12]:
distance_from_zero("cat")

Not possible


<hr style="border:5px solid #108999"> </hr>

# Sequences <hr style="border:4.5px solid #108999"> </hr>

## Lists

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

Create a list, called "Numbers". Let it contain the numbers 10, 25, 40, and 50.

In [1]:
Numbers = [10, 25, 40, 50]

Print the element at index 2 from the list.

In [2]:
Numbers[2]

40

Print the 0th element.

In [3]:
Numbers[0]

10

Print the third-to-last element using a minus sign in the brackets.

In [4]:
Numbers[-3]

25

Substitute the number 10 with the number 15.

In [5]:
Numbers[0] = 15
Numbers

[15, 25, 40, 50]

Delete the number 25 from the Numbers list.

In [6]:
del Numbers[1]
Numbers

[15, 40, 50]

## Help Yourself with Methods

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

Append the number 100 to the Numbers list. 

In [1]:
Numbers = [15, 40, 50]

In [2]:
Numbers.append(100)
Numbers

[15, 40, 50, 100]

With the help of the "extend method", add the numbers 115 an 140 to the list. 

In [3]:
Numbers.extend([115, 140])
Numbers

[15, 40, 50, 100, 115, 140]

Print a statement, saying "The fourth element of the Numbers list is:" and then designate the value of the fourth element. Use a trailing comma.

In [4]:
print ('The fourth element of the Numbers list is', Numbers[3])

The fourth element of the Numbers list is 100


How many elements are there in the Numbers list?

In [5]:
len(Numbers)

6

## List Slicing

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

In [1]:
Numbers = [15, 40, 50, 100, 115, 140]

Using list slicing, obtain the numbers 100 and 115.

In [2]:
Numbers[3:5]

[100, 115]

Using slicing, extract the first four elements from the list.

In [3]:
Numbers[:4]

[15, 40, 50, 100]

Using slicing, extract all the elements from the list from the 3rd position onwards.

In [4]:
Numbers[3:]

[100, 115, 140]

Using slicing, extract the last 4 elements from the list.

In [5]:
Numbers[-4:]

[50, 100, 115, 140]

Which is the position of the value 15?

In [6]:
Numbers.index(15)

0

Create a list, called "Two_Numbers". Let its elements be the values 1 and 2. Then, create a new one, named "All_Numbers", that will containt both the "Numbers" and the "Two_Numbers" lists. 

In [7]:
Two_Numbers = [1,2]
All_Numbers = [Two_Numbers, Numbers]
All_Numbers

[[1, 2], [15, 40, 50, 100, 115, 140]]

Sort all the numbers in the "Numbers" list from the largest to the smallest.

In [8]:
Numbers.sort(reverse=True)
Numbers

[140, 115, 100, 50, 40, 15]

## Tuples

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

Create a tuple, called "Cars", with elements "BMW", "Dodge", and "Ford". 

In [1]:
Cars = "BMW", "Dodge", "Ford"
Cars

('BMW', 'Dodge', 'Ford')

or:

In [2]:
Cars = ("BMW", "Dodge", "Ford")
Cars

('BMW', 'Dodge', 'Ford')

Access the second element of this tuple.

In [3]:
Cars[1]

'Dodge'

Call a method that would allow you to extract the provided name and age separately. Then print the "name" and "age" values to see if you worked correctly.

In [4]:
name, age = 'Peter,24'

ValueError: too many values to unpack (expected 2)

In [5]:
name, age = 'Peter,24'.split(',')

In [6]:
print (name)
print (age)

Peter
24


Create a function that takes as arguments the two values of a rectangle and then returns the Area and the Perimeter of the rectangle.
Call the function with arguments 2 and 10 to verify it worked correctly.

In [7]:
def rectangle_info(x,y):
    A = x * y
    P = 2 * (x + y)
    print ("Area and Parameter:")
    return A, P

In [8]:
rectangle_info(2, 10)

Area and Parameter:


(20, 24)

## Dictionaries

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

This is the menu of a close-by restaurant:

In [1]:
Menu = {'meal_1':'Spaghetti', 'meal_2':'Fries', 'meal_3':'Hamburger', 'meal_4':'Lasagna'}

What is the second meal in the list?

In [2]:
Menu['meal_2']

'Fries'

or:

In [3]:
print (Menu['meal_2'])

Fries


Add a new meal - "Soup".

In [4]:
Menu['meal_5'] = "Soup"
Menu

{'meal_1': 'Spaghetti',
 'meal_2': 'Fries',
 'meal_3': 'Hamburger',
 'meal_4': 'Lasagna',
 'meal_5': 'Soup'}

Replace the Hamburger with a Cheeseburger.

In [5]:
Menu['meal_3'] = 'Cheesburger'
Menu

{'meal_1': 'Spaghetti',
 'meal_2': 'Fries',
 'meal_3': 'Cheesburger',
 'meal_4': 'Lasagna',
 'meal_5': 'Soup'}

Attach the Desserts list in the form of a sixth meal.

In [6]:
Dessert = ['Pancakes', 'Ice-cream', 'Tiramisu']

In [7]:
Menu['meal_6'] = Dessert
Menu

{'meal_1': 'Spaghetti',
 'meal_2': 'Fries',
 'meal_3': 'Cheesburger',
 'meal_4': 'Lasagna',
 'meal_5': 'Soup',
 'meal_6': ['Pancakes', 'Ice-cream', 'Tiramisu']}

Create a new dictionary that contains the first five meals as keys and assign the following five values as prices (in dollars):
10, 5, 8, 12, 5. 
Start by *Price_list = {}*.

In [8]:
Price_list = {}
Price_list['Spaghetti'] = 10
Price_list['Fries'] = 5
Price_list['Cheesburger'] = 8
Price_list['Lasagna'] = 12
Price_list['Soup'] = 5
Price_list

{'Cheesburger': 8, 'Fries': 5, 'Lasagna': 12, 'Soup': 5, 'Spaghetti': 10}

or:

In [9]:
Price_list = {}
Price_list[Menu['meal_1']] = 10
Price_list[Menu['meal_2']] = 5
Price_list[Menu['meal_3']] = 8
Price_list[Menu['meal_4']] = 12
Price_list[Menu['meal_5']] = 5
Price_list

{'Cheesburger': 8, 'Fries': 5, 'Lasagna': 12, 'Soup': 5, 'Spaghetti': 10}

Use the *.get()* method to check the price of the Spaghetti.

In [10]:
Price_list.get('Spaghetti')

10

or:

In [11]:
Price_list.get(Menu['meal_1'])

10

<hr style="border:5px solid #108999"> </hr>

# Iteration <hr style="border:4.5px solid #108999"> </hr>

## For Loops

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

Create a For loop that prints every digit on a new line.

In [1]:
digits = [0,1,2,3,4,5,6,7,8,9]

In [2]:
for d in digits:
    print (d)

0
1
2
3
4
5
6
7
8
9


Adjust the code, so the digits are all printed on the same line.

In [3]:
for d in digits:
    print (d, end=" ")

0 1 2 3 4 5 6 7 8 9 

## While Loops and Incrementing

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

Create a while loop that will print all odd numbers from 0 to 30 on the same row. 
<br />
*Hint: There are two ways in which you can create the odd values!*

In [2]:
x = 1
while x <= 30:
    print (x, end=" ")
    x = x + 2

1 3 5 7 9 11 13 15 17 19 21 23 25 27 29 

or:

In [3]:
x = 1
while x <= 30:
    print (x, end=" ")
    x += 2

1 3 5 7 9 11 13 15 17 19 21 23 25 27 29 

## Create Lists with the range() Function

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

Use the range() function to create a list with all numbers from 1 to 10.

In [1]:
list(range(1,11))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Use the range() function to create a list with all numbers from 0 to 19.

In [2]:
list(range(20))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

Use the range function to create a list with all even numbers from 0 to 30 included.

In [3]:
list(range(0,31,2))

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30]

## Use Conditional Statements and Loops Together

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

Create a For loop that will print all the variables from a given list multiplied by 2. Let the list contain all numbers from 1 to 10. Create it with the help of the range() function.

In [1]:
for n in range(1,11):
    print (n * 2)

Create a little program that runs a loop over all values from 1 to 30. Let it print all Odd numbers, and in the place of the even numbers, it should print "Even".
Help yourself with the range() function to solve this exercise.

In [2]:
for x in range(1,31):
    if x % 2 == 1:
        print (x, end = " ")
    else:
        print ("Even", end = " ")

1 Even 3 Even 5 Even 7 Even 9 Even 11 Even 13 Even 15 Even 17 Even 19 Even 21 Even 23 Even 25 Even 27 Even 29 Even 

You have the following list of numbers. Iterate over this list, printing out each list value multiplied by 10.
Find two solutions of this problem.

In [3]:
n = [1,2,3,4,5,6]

In [4]:
for item in n:
    print (item * 10, end = " ")

10 20 30 40 50 60 

In [5]:
for item in range(len(n)):
    print (n[item] * 10, end = " ")

10 20 30 40 50 60 

## All in - Conditional Statements, Functions, and Loops

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

You are provided with the 'nums' list. Complete the code in the cell that follows. Use a while loop to count the number of values lower than 20. <br/>
*Hint: This exercise is similar to what we did in the video lecture. You might prefer using the x[item] structure for indicating the value of an element from the list.*

In [1]:
nums = [1,35,12,24,31,51,70,100]

In [2]:
def count(numbers):
    numbers = sorted(numbers)
    tot = 0
    
    while numbers[tot] < 20:
        tot += 1
    return tot

In [3]:
count(nums)

2

## Iterating over Dictionaries

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

In this exercise you will use the same dictionaries as the ones we used in the lesson - "prices" and "quantity". This time, don't just calculate all the money Jan spent. Calculate how much she spent on products with a price of 5 dollars or more.

In [1]:
prices = {
    "box_of_spaghetti" : 4,
    "lasagna"  : 5,
    "hamburger" : 2
   }
quantity = {
    "box_of_spaghetti" : 6,
    "lasagna"  : 10,
    "hamburger" : 0
    }

money_spent = 0

In [2]:
for i in quantity:
    if prices[i]>=5:
        money_spent += prices[i]*quantity[i] 
    else:
        money_spent = money_spent

print (money_spent)

50


And how much did Jan spent on products that cost less than 5 dollars?

In [3]:
prices = {
    "box_of_spaghetti" : 4,
    "lasagna"  : 5,
    "hamburger" : 2
   }
quantity = {
    "box_of_spaghetti" : 6,
    "lasagna"  : 10,
    "hamburger" : 0
    }

money_spent = 0

In [4]:
for i in quantity:
    if prices[i]<5:
        money_spent += prices[i]*quantity[i] 
    else:
        money_spent = money_spent

print (money_spent)

24
